### PR TITLE
Downgrade React dependency to React 16, as well as associated dependencies.

### PR DESCRIPTION
**Pull request by nicholas-yong**
As per title.

### CODE REVIEW

**Comment by exiadbq** [comment]
Question: I thought react got backwards compatibility. Or our codebase need to go react 18 etc.

**Review by lizacodes — APPROVED** [review]

**Comment by nicholas-yong** [comment]
@exiadbq we are currently on React 16 in Webapp and this package has a dependency on React 17. It does still work with React 16, but I wanted to downgrade it so we didn't need to use `--force` when doing `npm i`

**Comment by exiadbq** [comment]
@nicholas-yong Ideally we should move web app to the latest version of React and to not only reduce the effort of upgrade, but get the benefits of all libs that currently maintained and any performance improvement etc from react.

**Comment by nicholas-yong** [comment]
@exiadbq Yup definitely, I want to tackle that in a seperate ticket to this since we have a lot of project dependencies that are using 16x, and I think a seperate ticket would be the best way to tackle it.

**Pull request merged**
